### ISSUE TITLE
The width of the page is adjusted on the second column with the photo

### ISSUE THREAD

**Issue by koksikus** [codihaus/directus-extension-grid-layout#3]
When changing the width of the browser, all the process takes place on the field with the photo...

https://user-images.githubusercontent.com/90528895/227317322-f8e80ba6-ea53-4cb0-ab1a-a9427ff36ffc.mp4

**Comment by tusieunhan** [comment]
@koksikus Hi, thanks for the feedback on this bug, I will fix it in the next release. (today or tomorrow)
