### ISSUE TITLE
If a photo is missing in one of the records, an error appears in the console

### ISSUE THREAD

**Issue by koksikus** [codihaus/directus-extension-grid-layout#4]
![Zrzut ekranu 2023-03-23 195557](https://user-images.githubusercontent.com/90528895/227319655-0756f48e-042c-47c9-8af4-612ac082cf5b.png)
if there are photos in all records, then the error does not appear.

**Comment by tusieunhan** [comment]
Thank you for your feedback, I have fixed this error, install the latest version.

**Comment by codihaus** [comment]
fixed: #0a21da1
