### ISSUE TITLE
Text for a given relationship field is not in line with the rest of the text

### ISSUE THREAD

**Issue by koksikus** [codihaus/directus-extension-grid-layout#6]
As you can see in the attached screenshot, link "3 items" is a bit higher:
![Zrzut ekranu 2023-03-25 170726](https://user-images.githubusercontent.com/90528895/227728952-9205cb60-03c5-42c1-b0a9-8d434001f05e.png)

**Comment by codihaus** [comment]
Hello @koksikus , can you please check if this has been fixed in the latest version?

**Comment by vanling** [comment]
@codihaus  Looks good here
<img width="213" alt="image" src="https://github.com/codihaus/directus-extension-grid-layout/assets/50699657/882061a0-1704-4ee6-8e4a-a4e3ddaf0a3c">

**Comment by codihaus** [comment]
Awesome, I'm going to close the issue!
