### ISSUE TITLE
Suggestion: When a photo is missing, a replacement message should appear

### ISSUE THREAD

**Issue by koksikus** [codihaus/directus-extension-grid-layout#7]
At the moment, the field with the photo may be a bit confusing, i.e. whether the photo actually does not exist or maybe there is an error and it has not been downloaded. A nice option would be to upload, for example, a different (basic) photo or project icon.

![Zrzut ekranu 2023-03-25 170726](https://user-images.githubusercontent.com/90528895/227729482-4e5be983-7f12-4d55-9383-3638e893e2f9.png)

**Comment by codihaus** [comment]
@tusieunhan

**Comment by codihaus** [comment]
Hello @koksikus , team has fixed the issue, can you please check with latest version from npm?

**Comment by vanling** [comment]
@codihaus this is 'fixed' as in it shows an icon when there is no image in the selected source.
<img width="414" alt="image" src="https://github.com/codihaus/directus-extension-grid-layout/assets/50699657/9de0b5ed-0e49-4873-b73a-8b66d5fdaa93">

**Comment by codihaus** [comment]
Looks good. Since if has no image and we do not any image at all, it might affect to the layout.
Im going to close this, thanks @vanling
