### ISSUE TITLE
suggestion: If no photo source is selected, remove image and show card with only text 

### ISSUE THREAD

**Issue by vanling** [codihaus/directus-extension-grid-layout#8]
### Examples: 
<img width="1214" alt="Scherm­afbeelding 2023-03-28 om 10 50 01" src="https://user-images.githubusercontent.com/50699657/228182494-ddccbb62-3b13-4491-9da4-346487a8bc0a.png">

### Problem to solve:
What to do with the 'Selection icon'.
#### Possible solution:
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/50699657/228182925-b3c00c16-b860-4d76-8978-f34f90ddcaa3.png">

**_clarification:_** only when the source is empty, 
<img width="277" alt="Scherm­afbeelding 2023-03-28 om 10 59 45" src="https://user-images.githubusercontent.com/50699657/228185263-25460831-159b-4daf-8aad-9db555fe3dcf.png">

**Comment by codihaus** [comment]
@tusieunhan do you fixed ?

**Comment by codihaus** [comment]
Hello @vanling , can you please install the latest npm version and confirm this is fixed?

npm i directus-extension-grid-layout

**Comment by vanling** [comment]
@codihaus updated, it now shows an icon that @tusieunhan added. This ticket was a request to **hide the image** when no source was selected. 

It works, but it's not the change that this issue suggested.

**Comment by vanling** [comment]
@codihaus will close this suggestion, as it was only an suggestion and not so important.
